const mongoose = require('mongoose');
const dotenv = require('dotenv');
const User = require('./models/User');
const Product = require('./models/Product');
const connectDB = require('./config/db');

dotenv.config();
connectDB();

const seedAllCategories = async () => {
  try {
    let adminUser = await User.findOne({ isAdmin: true });
    if (!adminUser) {
      adminUser = await User.create({
        name: 'Admin User',
        email: 'admin@example.com',
        password: 'password',
        isAdmin: true,
      });
    }
    const adminId = adminUser._id;

    await Product.deleteMany();

    const productsToSeed = [
      // —— RINGS (6) — only ring photos ——
      {
        name: 'Diamond Solitaire Ring',
        image: '/images/rings_1.jpg',
        description: 'Round brilliant diamond solitaire in a classic four-prong setting.',
        brand: 'Aurora Custom',
        category: 'Rings',
        price: 2499,
        countInStock: 5,
        material: '18k White Gold & Diamond',
        user: adminId,
        seoTags: ['ring', 'diamond', 'solitaire'],
        metaTitle: 'Diamond Solitaire Ring | JEWELSAFA',
        metaDescription: 'White gold diamond solitaire engagement ring.',
      },
      {
        name: 'Gold Diamond Ring',
        image: '/images/rings_2.jpg',
        description: 'Yellow gold band with a bright center diamond and polished shoulders.',
        brand: 'Aurora Classic',
        category: 'Rings',
        price: 1899,
        countInStock: 7,
        material: '18k Yellow Gold & Diamond',
        user: adminId,
        seoTags: ['ring', 'gold', 'diamond'],
        metaTitle: 'Gold Diamond Ring | JEWELSAFA',
        metaDescription: '18k gold ring with center diamond.',
      },
      {
        name: 'Stainless Steel Band Ring',
        image: '/images/rings_3.jpg',
        description: 'Sleek silver-tone band with a single clear stone — durable daily wear.',
        brand: 'Aurora Modern',
        category: 'Rings',
        price: 89,
        countInStock: 40,
        material: 'Stainless Steel & CZ',
        user: adminId,
        seoTags: ['ring', 'stainless steel', 'band'],
        metaTitle: 'Stainless Steel Band Ring | JEWELSAFA',
        metaDescription: 'Minimal stainless steel band ring.',
      },
      {
        name: 'Rose Gold Wedding Band',
        image: '/images/rings_4.jpg',
        description: 'Smooth rose gold wedding band with a comfort-fit interior.',
        brand: 'Aurora Minimal',
        category: 'Rings',
        price: 420,
        countInStock: 18,
        material: '14k Rose Gold',
        user: adminId,
        seoTags: ['ring', 'wedding band', 'rose gold'],
        metaTitle: 'Rose Gold Wedding Band | JEWELSAFA',
        metaDescription: 'Comfort-fit rose gold wedding band.',
      },
      {
        name: 'Oval Cut Gemstone Ring',
        image: '/images/rings_5.jpg',
        description: 'Oval center stone in a slim bezel — modern east-west silhouette.',
        brand: 'Aurora Modern',
        category: 'Rings',
        price: 760,
        countInStock: 11,
        material: '14k Gold & Gemstone',
        user: adminId,
        seoTags: ['ring', 'oval', 'gemstone'],
        metaTitle: 'Oval Cut Gemstone Ring | JEWELSAFA',
        metaDescription: 'Oval bezel-set gemstone ring.',
      },
      {
        name: 'Halo Diamond Engagement Ring',
        image: '/images/rings_6.jpg',
        description: 'Center diamond surrounded by a micro-pavé halo on a tapered shank.',
        brand: 'Aurora Royal',
        category: 'Rings',
        price: 3100,
        countInStock: 4,
        material: 'Platinum & Diamond',
        user: adminId,
        seoTags: ['ring', 'halo', 'engagement'],
        metaTitle: 'Halo Diamond Engagement Ring | JEWELSAFA',
        metaDescription: 'Platinum halo diamond engagement ring.',
      },

      // —— NECKLACES (6) — only necklace / chain / pendant photos ——
      {
        name: 'Pearl Strand Necklace',
        image: '/images/pearl_necklace.png',
        description: 'Classic graduated pearl strand with a secure fishhook clasp.',
        brand: 'Aurora Classic',
        category: 'Necklaces',
        price: 1550,
        countInStock: 8,
        material: 'Freshwater Pearls',
        user: adminId,
        seoTags: ['necklace', 'pearl', 'strand'],
        metaTitle: 'Pearl Strand Necklace | JEWELSAFA',
        metaDescription: 'Graduated pearl strand necklace.',
      },
      {
        name: '18k Gold Chain Necklace',
        image: '/images/gold_necklace.png',
        description: 'Heavy curb-link chain in high-polish yellow gold.',
        brand: 'Aurora Classic',
        category: 'Necklaces',
        price: 899,
        countInStock: 12,
        material: '18k Yellow Gold',
        user: adminId,
        seoTags: ['necklace', 'gold chain'],
        metaTitle: '18k Gold Chain Necklace | JEWELSAFA',
        metaDescription: 'Solid gold curb chain necklace.',
      },
      {
        name: 'Sapphire Pendant Necklace',
        image: '/images/sapphire_pendant.png',
        description: 'Brilliant blue sapphire surrounded by diamonds on a fine gold chain.',
        brand: 'Aurora Royal',
        category: 'Necklaces',
        price: 1650,
        countInStock: 5,
        material: 'Gold & Sapphire',
        user: adminId,
        seoTags: ['necklace', 'pendant', 'sapphire'],
        metaTitle: 'Sapphire Pendant Necklace | JEWELSAFA',
        metaDescription: 'Blue sapphire pendant on gold chain.',
      },
      {
        name: 'Diamond Pendant Necklace',
        image: '/images/necklaces_4.jpg',
        description: 'Solitaire diamond on a fine cable chain with adjustable extender.',
        brand: 'Aurora Custom',
        category: 'Necklaces',
        price: 1280,
        countInStock: 9,
        material: 'White Gold & Diamond',
        user: adminId,
        seoTags: ['necklace', 'diamond', 'pendant'],
        metaTitle: 'Diamond Pendant Necklace | JEWELSAFA',
        metaDescription: 'Diamond solitaire pendant on cable chain.',
      },
      {
        name: 'Layered Gold Necklace',
        image: '/images/necklaces_5.jpg',
        description: 'Two-length layered chains with delicate disc charms.',
        brand: 'Aurora Modern',
        category: 'Necklaces',
        price: 340,
        countInStock: 20,
        material: '14k Gold Plated',
        user: adminId,
        seoTags: ['necklace', 'layered', 'gold'],
        metaTitle: 'Layered Gold Necklace | JEWELSAFA',
        metaDescription: 'Double-layer gold necklace.',
      },
      {
        name: 'Silver Rope Chain Necklace',
        image: '/images/necklaces_6.jpg',
        description: 'Twisted rope chain in bright sterling silver — unisex length.',
        brand: 'Aurora Modern',
        category: 'Necklaces',
        price: 120,
        countInStock: 25,
        material: '925 Sterling Silver',
        user: adminId,
        seoTags: ['necklace', 'silver', 'chain'],
        metaTitle: 'Silver Rope Chain Necklace | JEWELSAFA',
        metaDescription: 'Sterling silver rope chain necklace.',
      },

      // —— BRACELETS (6) — chain / cuff / tennis only (NOT bangles) ——
      {
        name: 'Diamond Tennis Bracelet',
        image: '/images/platinum_bracelet.png',
        description: 'Continuous line of round diamonds with a box safety clasp.',
        brand: 'Aurora Royal',
        category: 'Bracelets',
        price: 3499,
        countInStock: 3,
        material: 'Platinum & Diamond',
        user: adminId,
        seoTags: ['bracelet', 'tennis', 'diamond'],
        metaTitle: 'Diamond Tennis Bracelet | JEWELSAFA',
        metaDescription: 'Platinum diamond tennis bracelet.',
      },
      {
        name: 'Gold Link Chain Bracelet',
        image: '/images/bracelets_1.jpg',
        description: 'Interlocking gold links with a lobster clasp — classic men’s or women’s style.',
        brand: 'Aurora Classic',
        category: 'Bracelets',
        price: 680,
        countInStock: 14,
        material: '18k Yellow Gold',
        user: adminId,
        seoTags: ['bracelet', 'gold', 'chain'],
        metaTitle: 'Gold Link Chain Bracelet | JEWELSAFA',
        metaDescription: 'Gold link chain bracelet.',
      },
      {
        name: 'Pearl Line Bracelet',
        image: '/images/bracelets_2.jpg',
        description: 'Uniform freshwater pearls strung on silk with a gold clasp.',
        brand: 'Aurora Classic',
        category: 'Bracelets',
        price: 520,
        countInStock: 10,
        material: 'Pearls & Gold',
        user: adminId,
        seoTags: ['bracelet', 'pearl'],
        metaTitle: 'Pearl Line Bracelet | JEWELSAFA',
        metaDescription: 'Freshwater pearl bracelet.',
      },
      {
        name: 'Silver Cuff Bracelet',
        image: '/images/bracelets_3.jpg',
        description: 'Open cuff in brushed sterling with rounded edges.',
        brand: 'Aurora Modern',
        category: 'Bracelets',
        price: 145,
        countInStock: 22,
        material: '925 Sterling Silver',
        user: adminId,
        seoTags: ['bracelet', 'cuff', 'silver'],
        metaTitle: 'Silver Cuff Bracelet | JEWELSAFA',
        metaDescription: 'Sterling silver cuff bracelet.',
      },
      {
        name: 'Rose Gold Charm Bracelet',
        image: '/images/bracelets_4.jpg',
        description: 'Cable chain with heart and star charms in rose gold finish.',
        brand: 'Aurora Minimal',
        category: 'Bracelets',
        price: 210,
        countInStock: 18,
        material: 'Rose Gold Plated',
        user: adminId,
        seoTags: ['bracelet', 'charm', 'rose gold'],
        metaTitle: 'Rose Gold Charm Bracelet | JEWELSAFA',
        metaDescription: 'Rose gold charm bracelet.',
      },
      {
        name: 'Leather & Gold Bead Bracelet',
        image: '/images/bracelets_6.jpg',
        description: 'Braided leather wrap with gold-tone magnetic clasp and accent beads.',
        brand: 'Aurora Modern',
        category: 'Bracelets',
        price: 75,
        countInStock: 35,
        material: 'Leather & Gold Tone',
        user: adminId,
        seoTags: ['bracelet', 'leather', 'bead'],
        metaTitle: 'Leather & Gold Bead Bracelet | JEWELSAFA',
        metaDescription: 'Leather wrap bracelet with gold beads.',
      },

      // —— EARRINGS (6) — studs, hoops, drops ——
      {
        name: 'Diamond Stud Earrings',
        image: '/images/earrings_1.jpg',
        description: 'Matched pair of round brilliant studs in four-prong baskets.',
        brand: 'Aurora Custom',
        category: 'Earrings',
        price: 1899,
        countInStock: 6,
        material: 'White Gold & Diamond',
        user: adminId,
        seoTags: ['earrings', 'studs', 'diamond'],
        metaTitle: 'Diamond Stud Earrings | JEWELSAFA',
        metaDescription: 'Classic diamond stud earrings.',
      },
      {
        name: 'Gold Hoop Earrings',
        image: '/images/earrings_2.jpg',
        description: 'Medium tubular hoops with secure click-back posts.',
        brand: 'Aurora Classic',
        category: 'Earrings',
        price: 480,
        countInStock: 16,
        material: '18k Yellow Gold',
        user: adminId,
        seoTags: ['earrings', 'hoops', 'gold'],
        metaTitle: 'Gold Hoop Earrings | JEWELSAFA',
        metaDescription: 'Yellow gold hoop earrings.',
      },
      {
        name: 'Pearl Drop Earrings',
        image: '/images/earrings_3.jpg',
        description: 'Akoya pearls on gold posts with leaf-motif caps.',
        brand: 'Aurora Classic',
        category: 'Earrings',
        price: 920,
        countInStock: 9,
        material: 'Gold & Pearl',
        user: adminId,
        seoTags: ['earrings', 'pearl', 'drop'],
        metaTitle: 'Pearl Drop Earrings | JEWELSAFA',
        metaDescription: 'Pearl drop dangle earrings.',
      },
      {
        name: 'Silver Ball Stud Earrings',
        image: '/images/earrings_4.jpg',
        description: 'Polished sterling ball studs — everyday minimal pair.',
        brand: 'Aurora Minimal',
        category: 'Earrings',
        price: 45,
        countInStock: 50,
        material: '925 Sterling Silver',
        user: adminId,
        seoTags: ['earrings', 'studs', 'silver'],
        metaTitle: 'Silver Ball Stud Earrings | JEWELSAFA',
        metaDescription: 'Sterling silver ball stud earrings.',
      },
      {
        name: 'Emerald Stud Earrings',
        image: '/images/earrings_5.jpg',
        description: 'Square emeralds in bezel settings with diamond halos.',
        brand: 'Aurora Royal',
        category: 'Earrings',
        price: 1650,
        countInStock: 5,
        material: 'Gold & Emerald',
        user: adminId,
        seoTags: ['earrings', 'studs', 'emerald'],
        metaTitle: 'Emerald Stud Earrings | JEWELSAFA',
        metaDescription: 'Emerald halo stud earrings.',
      },
      {
        name: 'Crystal Drop Earrings',
        image: '/images/earrings_6.jpg',
        description: 'Elongated crystal drops on rhodium hooks for evening wear.',
        brand: 'Aurora Royal',
        category: 'Earrings',
        price: 280,
        countInStock: 14,
        material: 'Crystal & Rhodium',
        user: adminId,
        seoTags: ['earrings', 'drop', 'crystal'],
        metaTitle: 'Crystal Drop Earrings | JEWELSAFA',
        metaDescription: 'Evening crystal drop earrings.',
      },

      // —— BANGLES (6) — rigid wrist bangles, traditional style, different colours ——
      {
        name: 'Traditional Gold Bangles (Pair)',
        image: '/images/bangles_1.jpg',
        description: 'Classic hand-forged gold kangans with traditional engraving — worn as a pair.',
        brand: 'Aurora Heritage',
        category: 'Bangles',
        price: 3800,
        countInStock: 3,
        material: '22k Gold',
        user: adminId,
        seoTags: ['bangle', 'gold', 'traditional', 'kangan'],
        metaTitle: 'Traditional Gold Bangles | JEWELSAFA',
        metaDescription: '22k gold traditional bangle pair.',
      },
      {
        name: 'Colorful Glass Bangles Set',
        image: '/images/bangles_2.jpg',
        description: 'Set of bright glass churis in red, green, and gold tones for festive wear.',
        brand: 'Aurora Heritage',
        category: 'Bangles',
        price: 45,
        countInStock: 40,
        material: 'Glass',
        user: adminId,
        seoTags: ['bangle', 'colorful', 'glass', 'churi'],
        metaTitle: 'Colorful Glass Bangles Set | JEWELSAFA',
        metaDescription: 'Multicolor glass bangle set.',
      },
      {
        name: 'Red & Gold Bridal Bangles',
        image: '/images/bangles_3.jpg',
        description: 'Wide lac bangles in bridal red with gold dot work — South Asian wedding style.',
        brand: 'Aurora Heritage',
        category: 'Bangles',
        price: 65,
        countInStock: 30,
        material: 'Lac & Gold Tone',
        user: adminId,
        seoTags: ['bangle', 'bridal', 'red', 'lac'],
        metaTitle: 'Red & Gold Bridal Bangles | JEWELSAFA',
        metaDescription: 'Red lac bridal bangle set.',
      },
      {
        name: 'Silver Kada Bangles',
        image: '/images/bangles_4.jpg',
        description: 'Polished sterling kada bangles with a smooth rigid oval profile.',
        brand: 'Aurora Modern',
        category: 'Bangles',
        price: 180,
        countInStock: 18,
        material: '925 Sterling Silver',
        user: adminId,
        seoTags: ['bangle', 'silver', 'kada'],
        metaTitle: 'Silver Kada Bangles | JEWELSAFA',
        metaDescription: 'Sterling silver kada bangles.',
      },
      {
        name: 'Rose Gold Plated Bangles',
        image: '/images/bangles_5.jpg',
        description: 'Slim rose-gold-tone bangles with a soft mirror finish — set of four.',
        brand: 'Aurora Modern',
        category: 'Bangles',
        price: 95,
        countInStock: 25,
        material: 'Rose Gold Plated Brass',
        user: adminId,
        seoTags: ['bangle', 'rose gold', 'stacking'],
        metaTitle: 'Rose Gold Plated Bangles | JEWELSAFA',
        metaDescription: 'Rose gold tone slim bangle set.',
      },
      {
        name: 'Green Enamel Kundan Bangles',
        image: '/images/bangles_6.jpg',
        description: 'Green meenakari enamel with kundan stone inlay — festive traditional kada.',
        brand: 'Aurora Heritage',
        category: 'Bangles',
        price: 220,
        countInStock: 12,
        material: 'Brass, Enamel & Kundan',
        user: adminId,
        seoTags: ['bangle', 'kundan', 'green', 'enamel'],
        metaTitle: 'Green Enamel Kundan Bangles | JEWELSAFA',
        metaDescription: 'Green kundan enamel bangles.',
      },
    ];

    await Product.insertMany(productsToSeed);
    console.log(`Seeded ${productsToSeed.length} products — 6 per category, correct images only.`);
    process.exit(0);
  } catch (error) {
    console.error('Seeding failed:', error);
    process.exit(1);
  }
};

seedAllCategories();
